name             'apache2-global-customlog'
maintainer       'Simon Detheridge'
maintainer_email 'simon@widgit.com'
license          'Apache v2.0'
description      'Adds global CustomLog and LogFormat directives'
long_description 'Adds a global CustomLog and optionally one or more LogFormat directives to Apache\'s global config'
version          '0.1.0'
depends          'apache2', '>= 2.0.0'
provides         'apache2-global-customlog::default'
supports         'ubuntu'
supports         'debuan'
